### ISSUE TITLE
You're awesome

### ISSUE THREAD

**Issue by scuba-tech** [victornpb/undiscord#10]
Okay FINE, not an issue. I just wanted to say thanks. Had to nuke a #channel and this was the first script that I was able to understand (good for learning so thanks :) ) while reading through, and the UI was 👌👌👌👌👌👌👌👌👌👌 perfect.

So, uh, yeah. Thanks!  ^_^

**Comment by victornpb** [comment]
Thank you! I'm happy it worked for you, I put a lot of effort into making instruction as clear as possible, and making the UI comprehensible.
