### ISSUE TITLE
[BUG]  close a tab mid sequence it no longer clears messages for the specific dms with the other account

### ISSUE THREAD

**Issue by AftrMth** [victornpb/undiscord#102]
Once you close a tab mid sequence it no longer clears messages for the specific dms with the other account

1. Go to execute the script
2. Close tab mid script
3. Try and restart the script
5. (Do this on an alt account that you dont need all the messages gone from)

- [x ] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Windows 10
 - Browser: chrome 69

**Comment by Unearthly1995** [comment]
Does this work on servers you were banned from your original account?
