### ISSUE TITLE
Ended because API returned an empty page.

### ISSUE THREAD

**Issue by Yokoo2** [victornpb/undiscord#110]
I cant delete the chat because of an message that says "Ended because API returned an empty page." Is there a fix?

https://prnt.sc/ty8uxg

**Comment by itzTheMeow** [comment]
it looks like your guild ID is only 3 characters long, that's too short. Try copying the ID again.

**Comment by chungdublo** [comment]
The guild ID in that screenshot is ony 3 characters because it is "@me" indicating a direct message thread. I was able to find a workaround for this issue and will paste my comment from issue #112 : 

> I was also experiencing this issue. I had about 22k messages to delete and got it down to 8k after running it for about a day. Then the API started returning an empty page.
> 
> I was able to fix this by first finding my message the script had stopped on and copying its ID. Then I set it to delete all messages before that one. It worked normally again after that. I was able to find it using discord's search features, to look for messages by me.
> 
> I think what might have been happening was that there were just so many messages between the present and where it stopped deleting messages that it was not able to go that far back and find my messages anymore. I had already deleted like 3 years of messages so it was trying to read messages back from 2020 to find where it had left off, which was in like early 2017.
> 
> I hope this makes sense and helps someone experiencing the same issue.
