### ISSUE TITLE
BD support

### ISSUE THREAD

**Issue by ghost** [victornpb/undiscord#111]
Can we PLEASE get this in a form of JS that we can use with better discord, I hate using the browser and from my uneducated thought process it looks like it would work with BD. The only user input I can think of into getting it to work in BD is the token, what I'm thinking is if you move the script to the BD plugins folder and then right-click and edit the JS and add your token then save it. In my opinion, it seems like it will and can work, it just doesn't have implementation? Please i BEG you add this as a plugin that works with BD.

**Comment by victornpb** [comment]
I never used BD, it's something I'll have to look into, if it's not too much work I can probably port it.

The script already works on the App if you enable dev mode and paste it into the console. But you have to do it every time you open it, that's why I went to the browser extension route, because you only install it once.

**Comment by Technetium1** [comment]
That's very very possible! @victornpb [this](https://github.com/rauenzi/BetterDiscordApp/wiki) will set you in the right direction. Make sure you follow the addon policies to be listed as an official extension!

**Comment by 0ghj04hjyg9045** [comment]
Any update on this? This would be awesome if possible.

**Comment by Technetium1** [comment]
There are *lots* of huge changes going on with BBD right now, I'd recommend waiting a couple of weeks minimum before trying to implement something.

**Comment by 7MXek** [comment]
I navigated here from a Google search for exactly this. This issue is still listed as open so I am resurrecting this thread to add that an Undiscord plugin for BetterDiscord would be great! Is there any update?

**Comment by Technetium1** [comment]
Update: Discord just did a MAJOR update of internals, which has almost entirely broken BBD. There's no ETA on a fix, so it's a very bad moment to make or integrate anything new. Probably going to be _at least_ 2 more weeks until it's 'stable'.
