### ISSUE TITLE
[BUG] error searching messages api responded with status 404 message 404 not found code 0

### ISSUE THREAD

**Issue by merbra** [victornpb/undiscord#114]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

**Describe the bug**

**To Reproduce**

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.

```
Paste logs here
```

**Affects** (Add an X to items that apply)
- [ ] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: [e.g. Windows 10, macOS 10.15.0]
 - Browser [e.g. chrome 69, firefox 42.0]

**Comment by Cebtenzzre** [comment]
Make sure your channel ID and guild ID are correct. Those being wrong will produce this error.
