### ISSUE TITLE
[BUG] Discord limiting API response, causing messages to delete extremely slowly.

### ISSUE THREAD

**Issue by ghost** [victornpb/undiscord#118]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

**Describe the bug**
Discord may be limiting the rate at what you may be able to delete at sadly, unless it's just a new error within the code, you should look into this.

**To Reproduce**
1. Go to a channel.
2. Click on everything to run the script
3. Scroll down the log, after a few minutes you'll see the a rate limit between 4000-6000, which impacts deletion speed.

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.
![image](https://user-images.githubusercontent.com/69077979/91924754-24d03e00-ec99-11ea-8650-48d895b890df.png)

now the dates are messing up to 2085 and 2017 despite no messages being in 2019 or lower, only 2020.

```
Paste logs here
You're being rate limited to 5643ms.
```

**Affects** (Add an X to items that apply)
- [x] DMs
- [x] DM Groups
- [x] Channel
- [x] Channel (NSFW)
- [x] Server (All Channels)
- [x] Other (explain)

**System:**
 - OS: [CrOS]
 - Browser [newest Chrome version]

**Comment by whalehub** [comment]
Yeah, I can confirm this bug. If one allows DDM to delete messages as fast as possible, it'll continously hit the rate limits and reach a delay somewhere in the 4-12 seconds range which is never lowered again. After a bit of testing, I've found that manually adjusting the delay to around 1500ms (1.5s) allows the script to work through thousands of messages without hitting Discord's rate limits.

@victornpb I think a potential solution would be to add a new form field where users can enter a custom delay to deal with server-side rate limit changes like this.

**Comment by gAVINpentesting** [comment]
yeah probably, you can also set it to 600ms to get a few quick messages in it before the API limit gets automatically set to 1.5 or 1.6. And turning it off, refreshing or moving channels, and turning it back on brings it back up to a bit quicker to help it, sadly moving through 20k messages takes like 6 hours now. You could probably find a loophole to the API limit as well, though I haven't a clue what that would be. Maybe send an email to Discord support saying that deletion is too slow manually, and maybe they'll boost it back to what it was slightly, no clue. Your reply did help me though, whalehub! Thank you, or otherwise I wouldn't have thought of editing the code myself lol.

**Comment by andrewkm** [comment]
@victornpb please add a new form field for a custom delay.

**Comment by IvoryOwl92** [comment]
I've been having the same issue as well. It's strange because it wasn't always the case.

I'm on Firefox 80.0.1 (x64) and my Discord version appears to be the one from August 10th (according to the Change Log).
I followed Whalehub's advice and changed the deleteDelay to about 1000ms and searchDelay to 500 (not sure if the latter is necessary). It's much slower now but at least it deletes at a constant pace without errors and having to stop/start the script several times.

**Comment by 6kbyte** [comment]
> After a bit of testing, I've found that manually [adjusting the delay](https://github.com/victornpb/deleteDiscordMessages/blob/master/deleteDiscordMessages.user.js#L34) to around 1000ms (1s) allows the script to work through thousands of messages without hitting Discord's rate limits.
> 

How can i add this? Unfortunately I am not very familiar with scripts.

**Comment by IvoryOwl92** [comment]
@6kbyte 
Open Discord on a webpage (the desktop app won't do). The tampermonkey extension icon will show up with a red 1, click on it and then right-click on the Undiscord script. This will open up a page with a bunch of parameter lines. Search for deleteDelay and change the value from 100 to 1000.

Click on File in the top left corner of the script and Save. Close the script page and close the Discord tab (for it to refresh and accept the new values).

**Comment by 6kbyte** [comment]
@IvoryOwl92 thank you for your answer. I changed the value to 1000 but after that a saw a strange behavior: the script delete 10-20 messages, stops and automatically increase the waiting time... deletes 10-20 messages again, stops and automatically increase the waiting time... and so on. Result is that after a while you have to wait quite a long time until further deleting is done. Did i do something wrong?

**Comment by whalehub** [comment]
@6kbyte If you're still hitting the rate limits with a value of 1000, you need to increase it a bit. Try it with a value of 1250 or 1500.

Discord changes the rate limits on their API from time to time, so a value that worked one day can stop working the next.

**Comment by IvoryOwl92** [comment]
@6kbyte 
That's the exact same issue we've been having and why this thread was made. Whalehub's advice was supposed to be a workaround. Why do you say it's strange behavior now? Wasn't that the reason that lead you here, wanting to change the script in the first place? In any case, on top of the previous advice, I also changed the searchDelay to 300. (I said 500 in my earlier post but 300 seems to be working as well.) Try doing that as well? Don't forget to save the script and close your web browser (to refresh). Then try mass deleting messages again. 

If that doesn't work, then I'm out of ideas.

**Comment by victornpb** [comment]
Currently there is only a mechanism to increase the delay once you get throttled, but it doesn't go back down. 

I think I could implement some kind of decay, so it stays always at the optimum speed instead of just relying on a high delay number.

But testing will be required. Volunteers are appreciated, that way I don’t need to artificially create a bunch of messages in order to test.

Ill try to get back to this later, I only have time to work this on my spare time on weekends.

**Comment by Broine1** [comment]
i have been having this exact issue for a few weeks now. I've tried adjusting the delay to even 2000ms but i still get the same delay of around 70000ms or something similar after about 1 page of messages

**Comment by whalehub** [comment]
@Broine1 Are you deleting your own messages or other people's messages as a mod in a server? The latter requires a delay of around 5000ms to work continuously because the rate limits are much stricter.

**Comment by Broine1** [comment]
ah i see, yes i am deleting others messages (my own messages with an alt just in case) i will try using my own account

**Comment by mattiasduerrmeier** [comment]
Same issue for me as well, using the older script method.
I will gladly help with testing.

**Comment by demokert** [comment]
> 
> 
> Currently there is only a mechanism to increase the delay once you get throttled, but it doesn't go back down.
> 
> I think I could implement some kind of decay, so it stays always at the optimum speed instead of just relying on a high delay number.
> 
> But testing will be required. Volunteers are appreciated, that way I don’t need to artificially create a bunch of messages in order to test.
> 
> Ill try to get back to this later, I only have time to work this on my spare time on weekends.

Any update regarding this issue? :)

**Comment by Ammako** [comment]
Something causes the delay to lower itself from the default delay sometimes, for some reason. I've set my delay to 1000 to avoid rate limiting, but after a while it just starts deleting much quicker than the 1000 delay implies, and quickly gets stuck on the rate limiter which eventually rises to 4000+

![image](https://user-images.githubusercontent.com/43770697/99308274-a4f55100-284f-11eb-9c47-90ed3e444b50.png)

You can't really see it in the screenshot, but I'm watching it go and for no reason it just suddenly ignores my 1000ms delay and starts deleting messages really fast when it shouldn't. It doesn't happen all the time, so I'm not sure it could even be reproduced reliably, and so far it's only happened when I've had `has: link`, `has: file` and `include pinned` checked.

**Comment by victornpb** [comment]
> Something causes the delay to lower itself from the default delay sometimes, for some reason.

Yeah this is an oversight when I accepted the PR that allowed the user to enter manually a delay. it didn't take into consideration that the code previously tried to auto adjust the delay based on the rate limit responses. So this part of the code should have been modified as well. Ty for reporting that screenshot

**Comment by AirikWarren** [comment]
I think it's very likely that the constant rate of deletion is now being used as a factor used by Discord when choosing to limit user account's access to the API. I hacked together a quick and dirty fix, you can read about it / set it up here. 

https://github.com/victornpb/deleteDiscordMessages/issues/155#issuecomment-757382923

**Comment by andrewkm** [comment]
@victornpb please add this :) ^^^

**Comment by AirikWarren** [comment]
> 
> 
> @victornpb please add this :) ^^^

Were you having issues before and did my gist fix it? I can submit my own pull request once I confirm that it's not just a placebo.

**Comment by victornpb** [comment]
> > 
> 
> > 
> 
> > @victornpb please add this :) ^^^
> 
> 
> 
> Were you having issues before and did my gist fix it? I can submit my own pull request once I confirm that it's not just a placebo. 

I'm currently dealing with a personal matter, so I can't test anything atm. 

But I can take a look at your PR, and merge it if anyone can confirm it is working

**Comment by AirikWarren** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > @victornpb please add this :) ^^^
> > 
> > 
> > Were you having issues before and did my gist fix it? I can submit my own pull request once I confirm that it's not just a placebo.
> 
> I'm currently dealing with a personal matter, so I can't test anything atm.
> 
> But I can take a look at your PR, and merge it if anyone can confirm it is working

There is no PR as of this moment because my hacked together Gist was written just for me and is 
1) based on the less supported of the two codebases
2) uses defaults that may be way too high for some people

I'm going to start a new issue and see if I can't get any volunteers to try out the changes / see how widespread the new rate limiting is before I put in the effort to write good public facing code that plays nice with the existing codebase.

**Comment by andrewkm** [comment]
> > @victornpb please add this :) ^^^
> 
> Were you having issues before and did my gist fix it? I can submit my own pull request once I confirm that it's not just a placebo.

Yes, yours fixed my issues completely.

**Comment by AirikWarren** [comment]
> > > @victornpb please add this :) ^^^
> > 
> > Were you having issues before and did my gist fix it? I can submit my own pull request once I confirm that it's not just a placebo.
> 
> Yes, yours fixed my issues completely.

Awesome, I'll get started on a Pull Request this weekend

**Comment by PureFallen** [comment]
> 
> 
> > > > @victornpb please add this :) ^^^
> > > 
> > > 
> > > Were you having issues before and did my gist fix it? I can submit my own pull request once I confirm that it's not just a placebo.
> > 
> > 
> > Yes, yours fixed my issues completely.
> 
> Awesome, I'll get started on a Pull Request this weekend

I wonder if the Quick and Dirty Fix previously mentioned turned out to be functional in the testing.
Did the PR turn out to create issues when implementing?
