### ISSUE TITLE
Premature "Empty Page" Bug

### ISSUE THREAD

**Issue by Nathan442** [victornpb/undiscord#122]
**Describe the bug**

When I attempt to start deleting messages it just does this? It essentially won't start.
![hhhhhhh](https://user-images.githubusercontent.com/70959192/92597236-01ac1c80-f29f-11ea-8720-b82064230146.PNG)

```
Paste logs here
```

**Affects** (Add an X to items that apply)
- [x] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Windows 10
 - Browser Microsoft Edge

**Comment by Balls0fSteel** [comment]
Please tick "NSFW" mode in the toggles. That helped for me.

**Comment by Goddamnit44** [comment]
Yeah tried that and it didn't make a difference.

**Comment by jacknight** [comment]
You have channel ID filled out there. Are you sure you have messages in that particular channel of the discord server? If you remove channel ID entirely (and as mentioned earlier, include NSFW channels) does it find messages to delete?

**Comment by Nathan442** [comment]
Okay it is not a discord server its DM's and yes I have tried removing channel ID and marking it as NSFW. Neither works.

**Comment by chungdublo** [comment]
#112

**Comment by qyZMVYcw1VA6** [comment]
also experiencing this issue (DMs). mine seems to not detect any messages per page, but the total # of messages is detected.

![image](https://user-images.githubusercontent.com/47117778/98567240-b0f47800-227d-11eb-9c9d-de6e53ad9ee3.png)

**Comment by samueleyeam** [comment]
I was having this issue and I was able to work around it by setting the range to 2015 (doubt the start date matters) and then the day after the message it was tripping up on. So messages weren't being detected before 2/11/20, but I set the range 1/1/2015 to 2/12/2020 and it continued until some other message. I'm not sure what is causing this as I don't see any correlation between the areas it has been tripping up on, but hope it helps!

**Comment by Ammako** [comment]
I get that "empty page" is the finish condition for the script, but I think if the script can detect that the current page contains 25 system messages (call logs), it should continue searching for messages onto the next page instead of stopping. It should only stop if it reaches an empty page with zero system messages.

**Comment by Nathan442** [comment]
Has anyone figured out this problem yet?

**Comment by frederickpelchat** [comment]
I had the same problem and by setting a date range: very early start date and an end date close to where the last message could be found, fixed it for me. The script started deleting the left over messages.
