### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by 3Trex** [victornpb/undiscord#123]
Hi, everyone I have a little issue during deleting the messages, The console says I have a high ping? I'm not sure what's going on but it deletes the messages very slow, it used to be more faster. I don't download anything so I'm not sure about the issue.
Can you help me? I send a image as attached. 

Thanks!
![firefox_nHJXqhgviD](https://user-images.githubusercontent.com/43248490/92599163-c19a6900-f2a1-11ea-9e94-d5751824819c.png)

**Comment by Balls0fSteel** [comment]
**Not a bug.** Discord has been awfully slow in response time lately. Started happening a few days ago. This is why channels load slow, and this also slows down the deletion by unDiscord.

**Comment by whalehub** [comment]
Duplicate of #118.

**Comment by AtlantaGG** [comment]
Seems to happen to me too.
