### ISSUE TITLE
Reaction Feature

### ISSUE THREAD

**Issue by HideakiAtsuyo** [victornpb/undiscord#124]
Not really a problem just a feature.

It would be nice to also be able to remove reactions from messages that are not ours, add this as a checkbox !

**Comment by HideakiAtsuyo** [comment]
And for screenshot mode: https://i.imgur.com/GVfRWYi.png
Hide also the pixelated information on this picture

**Comment by itzTheMeow** [comment]
> And for screenshot mode: https://i.imgur.com/GVfRWYi.png
> Hide also the pixelated information on this picture

This was a bug, the checkbox started as checked, and if you unchecked the box, it redacted the info.

**Comment by HideakiAtsuyo** [comment]
> 
> 
> > And for screenshot mode: https://i.imgur.com/GVfRWYi.png
> > Hide also the pixelated information on this picture
> 
> This was a bug, the checkbox started as checked, and if you unchecked the box, it redacted the info.

oh in this case yeah need a fix like a var with the state of the checkbox and a if statement :)

**Comment by itzTheMeow** [comment]
was already fixed

**Comment by HideakiAtsuyo** [comment]
> 
> 
> was already fixed

True but:

"It would be nice to also be able to remove reactions from messages that are not ours, add this as a checkbox !"

can be a good thing :)

**Comment by itzTheMeow** [comment]
> "It would be nice to also be able to remove reactions from messages that are not ours, add this as a checkbox !"

Again, it is literally NOT POSSIBLE.

**Comment by HideakiAtsuyo** [comment]
> 
> 
> > "It would be nice to also be able to remove reactions from messages that are not ours, add this as a checkbox !"
> 
> Again, it is literally NOT POSSIBLE.

False 😂

**Comment by itzTheMeow** [comment]
not in DMs, and most people would use this in a DM, bots are for removing reactions...

**Comment by eiqnepm** [comment]
Is this currently possible?

**Comment by DeathDragonAW** [comment]
Would like to know where/how? I was about to request this as well.

**Comment by AerialJustice** [comment]
<img width="1054" height="610" alt="Image" src="https://github.com/user-attachments/assets/0ad43b1c-0a83-4231-95bd-9e8c5ec76d75" />
<img width="948" height="532" alt="Image" src="https://github.com/user-attachments/assets/e6816141-f78e-4997-9ecf-8a902fc50050" />
