### ISSUE TITLE
Request - nuclear option

### ISSUE THREAD

**Issue by EatDesk** [victornpb/undiscord#13]
Possible to add a nuclear option? Delete from everywhere: all servers, all channels, all dms. 

Possibly with an exclude list in case you want to leave one server/chat/dm untouched for example.

**Comment by victornpb** [comment]
There's no straightforward way of discovering all guilds (servers and DMs). But it is possible to discover all messages in the current server without having to specify each channel. I'll work on it.

**Comment by enemy1337** [comment]
I'd also like to see this implemented, if it's not too hard.

**Comment by DooML** [comment]
I guess all channels IDs are in the data you can download from Discord, might as well use it to delete everything ?

**Comment by victornpb** [comment]
@doomlerd theoretically yeah, but sometimes things are not that straightforward. Discord code is generated by tools a.k.a web pack, and it is minified. They also like to burry a few things, like getting the authToken with a click of a button required me to debug and step into dozens of obfuscated/minified files, until I was able to find a reliable way of accessing it.

**Comment by nektro** [comment]
any updates?

**Comment by grravity** [comment]
>But it is possible to discover all messages in the current server without having to specify each channel. I'll work on it.

Hope to see this

**Comment by Redactedd** [comment]
We need this.

**Comment by Redactedd** [comment]
> > But it is possible to discover all messages in the current server without having to specify each channel. I'll work on it.
> 
> Hope to see this, great for groups with a million channels.

Yeah

**Comment by nektro** [comment]
> There's no straightforward way of discovering all guilds (servers and DMs).

https://discord.com/developers/docs/resources/user#get-current-user-guilds ?

**Comment by victornpb** [comment]
I merged a PR in #88 #18 to import a list of channels from a json file.
https://github.com/victornpb/deleteDiscordMessages/blob/master/help/channelId.md#deleting-all-messages-by-using-the-request-a-copy-of-your-data-option

**Comment by intelfierce** [comment]
> I merged a PR in #88 #18 to import a list of channels from a json file.
> https://github.com/victornpb/deleteDiscordMessages/blob/master/help/channelId.md#deleting-all-messages-by-using-the-request-a-copy-of-your-data-option

Importing the json file doesn't work
