### ISSUE TITLE
[Question] CLI options?

### ISSUE THREAD

**Issue by ylluminate** [victornpb/undiscord#130]
Is there a way to operate this or any kind of delete function from the CLI similar to how this works?:
https://github.com/Tyrrrz/DiscordChatExporter/wiki/macOS-usage-instructions

Notice how the command line works:
```
dotnet DiscordChatExporter.Cli.dll export -t TOKEN -c CHANNEL
```

**Comment by whalehub** [comment]
@ylluminate Maybe this tool suits your needs: https://github.com/adversarialtools/discord-delete
