### ISSUE TITLE
[BUG] Error 500 stopping script

### ISSUE THREAD

**Issue by OstrichRider** [victornpb/undiscord#132]
Getting error 500 from Discord for searches after a while and it stops the script. Can't really leave it to do it's thing if I have to restart it all the time. If I wait 30 seconds searches start to work again so adding the option to retry 30 seconds after error 500 seems like a decent fix.

**Comment by OstrichRider** [comment]
Also just got "delete request throwed an error: {"stack":"typeerror: Failed to fetch","message":"failed to fetch"}

That also stopped the script

**Comment by SpicyBigGithub** [comment]
I'm also having this issue
