### ISSUE TITLE
Ability to target multiple servers

### ISSUE THREAD

**Issue by hartlomiej** [victornpb/undiscord#134]
A feature which would allow to just target all channels in multiple servers in sequence by separating them with a comma would be great. 
As far as I know, it's only possible to do that with channels in a single server.

I obviously requested for the data package to use it with `Import`, but it takes a lot of time to receive it.

Cheers.

**Comment by victornpb** [comment]
Yes it is kinda undocumented but you can separate guid ids by comma.

It was requested by another user, I implemented it but I didn't hear back from him if it worked.

So any feedback is appreciated, because it is not easy to test it on my end, as I don’t have anything to delete anymore...

**Comment by hartlomiej** [comment]
![screenshot](https://cdn.discordapp.com/attachments/619963477489877003/771495917982318602/unknown.png)

Tried it, returns error 400 with message "Value "x, y" is not a snowlake."
