### ISSUE TITLE
Copying deletion log

### ISSUE THREAD

**Issue by kirikomori** [victornpb/undiscord#141]
Thank you for the excellent script/app. Could you add a feature where you can save the deletion log?

**Comment by victornpb** [comment]
I'll add it as a enhancement, for now u can always copy/paste the entire thing

**Comment by kirikomori** [comment]
I don't see any way to copy the log, you can't highlight it

**Comment by AdaptiveAlchemist** [comment]
> I don't see any way to copy the log, you can't highlight it

Same here. You can't select the text. I request this feature too.

**Comment by chaitan94** [comment]
If it helps, I was able to do this via this workaround for now:

1. Copied the whole logarea element as html via the browser's Dev Tools. That is, everything in between `<pre class="logarea">` and `</pre>`
1. Converted it to plain text: https://templates.mailchimp.com/resources/html-to-text/

![image](https://user-images.githubusercontent.com/3336879/102711213-db563e00-42dd-11eb-963b-53a78f178b30.png)

**Comment by AdaptiveAlchemist** [comment]
> If it helps, I was able to do this via this workaround for now:
> 
> 1. Copied the whole logarea element as html via the browser's Dev Tools. That is, everything in between `<pre class="logarea">` and `</pre>`
> 2. Converted it to plain text: https://templates.mailchimp.com/resources/html-to-text/
> 
> ![image](https://user-images.githubusercontent.com/3336879/102711213-db563e00-42dd-11eb-963b-53a78f178b30.png)

Thanks for the help. I tried to do something similar but I don't understand html so I couldn't.
