### ISSUE TITLE
Proposal - Queue/Slow mode

### ISSUE THREAD

**Issue by Kein** [victornpb/undiscord#149]
It is a no-secret that Discord has a very loose definition of "selfbot". You, hammering their userAPI, can easily be considered as one. Now, to be frank, I haven't heard yet of anyone being banned for deleting their own messages, even in such ridiculous amount as 50k+, still, the only reason these account bans are not common is because Discord does not want [some reddit drama](https://www.reddit.com/r/pcgaming/comments/b7eeii/discord_wants_to_censor_harmless_speech_while_the/) about them being le `data-hoarding nazi and violating some GDRP memes`.

**Proposal**
Implement a queue/slow mode that will imitate manual human deletion. Obviously, you cant fool Discord itself, they have a few years of pattern recognition and mapping experience (yes, they do profile you even if you use browser version and can detect any userscripts and modifications), but at least, in worst case scenario, they cant drive an argument "*you hammered their use API and disrupted experience for everyone else*"

**Comment by Unearthly1995** [comment]
Is there any way to delete messages from a server you where bannned from?
