### ISSUE TITLE
It's not deleting anymore messages when there is a lot more

### ISSUE THREAD

**Issue by TMCFireYTV** [victornpb/undiscord#153]
everytime I try to delete messages it says Ended because API returned an empty page how do i fix this

**Comment by WukokoBaller** [comment]
i'm having the same issue only just recently, it was working fine before today (dec 14th 2020)

**Comment by WukokoBaller** [comment]
i noticed the discord channel link now has an additional set of numbers added to the original link, i dont know if thats relevant to this issue, but it's the only difference i could spot.

**Comment by WukokoBaller** [comment]
Okay i think i figured out a way to fix it, scroll up the last message it stopped at and just copy the message ID then paste that for the range and it'll start working again, at least for my case.

**Comment by GivingCash** [comment]
This is happening with me, I deleted 2k of 4k messages and the log posted below:

"Ended because API returned an empty page"

**Comment by Radioactiveglue** [comment]
Im also getting the same exact results, any way of fixing this or do we have to manually go back to deleting everything very slowly?

**Comment by WukokoBaller** [comment]
> Im also getting the same exact results, any way of fixing this or do we have to manually go back to deleting everything very slowly?

scroll up to the last message it stopped deleting at, copy the message ID and paste it in the before range and then hit start.
