### ISSUE TITLE
How does it get the token from localstorage?

### ISSUE THREAD

**Issue by DanDevDan** [victornpb/undiscord#162]
How does the popup get access to the local storage token? I cannot find any line in the html that would populate the local storage. Please help me understand how.

**Comment by AirikWarren** [comment]
here is the relevant code 

```js
    $('button#getToken').onclick = e => {
        window.dispatchEvent(new Event('beforeunload'));
        $('input#authToken').value = JSON.parse(popup.localStorage.token);
    };
 ```
It's parsing a JSON file, not HTML. You can see the JSON file that it is parsing by opening up Discord inside of your web browser and accessing the developer tools  and navigating to the "local storage" section.

**Comment by DanDevDan** [comment]
I get that. But the local storage does not contain the token on Discord. But for some reason the token appears in the popup's localstorage. That's what I don't get.
