### ISSUE TITLE
[BUG] "Stopped by you" when using imported json

### ISSUE THREAD

**Issue by cubednet135** [victornpb/undiscord#163]
When I import a JSON, I get a "Stopped by you" in every channel where there is messages and it never deletes.

**To Reproduce**
1. Go to a regular channel and start a deletion because for some reason importing the json without doing this doesn't work
2. Import the JSON
3. Start the deletion

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.

```
![image](https://user-images.githubusercontent.com/48071889/103709190-a30a5d00-4f77-11eb-9164-420c1daa95f9.png)
```

**Affects** (Add an X to items that apply)
- [X] DMs
- [X] DM Groups
- [X] Channel
- [X] Channel (NSFW)
- [X] Server (All Channels)
- [X] Other (explain)

**System:**
 - OS: [Windows 10, macOS 10.15.7]
 - Browser [Chrome 87]

**Comment by AirikWarren** [comment]
Are you utilizing a JSON script that you got from your data package, if so which one? 

I've run into similar issues when attempting to delete messages from multiple channels and temporarily mitigated it by disabling the "Stop" button function altogether but this is obviously less than ideal.

**Comment by cubednet135** [comment]
I'm using index.json which is what the wiki says to use.

**Comment by AirikWarren** [comment]
There are multiple "index.json" files within the data package. The entire folder should look like this.

```
package
| 
|    README.txt
|
└-----account
 |
└-----messages 
 |   └----[a bunch of directories]
 |             | index.json 
 |
└-----programs
 |
 └-----servers
      └----[a bunch more directories]
               | index.json
```

Was it under the servers director or the messages directory?
