### ISSUE TITLE
Delete only if Regular Expression Matches

### ISSUE THREAD

**Issue by SethFalco** [victornpb/undiscord#170]
**Is your feature request related to a problem? Please describe.**
There are some occasions where it can be useful to delete some messages in bulk in a channel, but only if it matches a regular expression.

For example:
* API keys, such as Discord bot tokens, AWS, Google, etc
* Specific uses of bot commands, such as `^[$%!/><]\s*ping$` to remove ping commands, but not other messages that use the word. 
* Personal information, such as phone numbers, postal codes, or email addresses sent by a person.

**Describe the solution you'd like**
I think it'd be great if an additional field could be added called "Pattern". 

The script can search for messages with the existing logic, but if "Pattern" is configured, then conditionally only delete messages if the pattern matches against the message contents, otherwise skips to the next.

**Comment by victornpb** [comment]
I like the idea
