### ISSUE TITLE
[BUG] Deletion process fails to start when the first 25 messages it finds are system messages (such as calls)

### ISSUE THREAD

**Issue by DADESUPER** [victornpb/undiscord#186]
I think i found the reason why some people report the app fails to delete messages despite there being more in the search results: if the first 25 messages it finds are all system messages (such as those about calls) it stops the process immediately. This prevents you from being able to find and delete messages once you reach 25 calls in a channel. A workaround is to refine search terms such that there are less than 25 system messages to start with.

This doesn't affect processes already started as far as i can see as it sets an "offset" on the search results. A possible fix for this could be checking for and (if necessary) setting an offset if the api returns an empty page, before stopping the process if no offset was added.

I suppose the same bug would also happen if at any point during the process there was a search result page full of calls.

**Comment by meganinj4** [comment]
Can confirm it, when skipping some call messages using the messages ID filter it starts working again for a bit, but when other call messages show up the system gives "ended because api returned an empty page" error over and over

**Comment by NelsonL97** [comment]
Has the fix for this suggested by the OP been implemented? @victornpb

**Comment by aaa234243** [comment]
Yea i'm having this issue too but i've tried it on areas where there are no calls and still doesn't work if thats what you guys meant
