### ISSUE TITLE
[BUG] Cannot delete Deleted User messags

### ISSUE THREAD

**Issue by Dreamurrrr** [victornpb/undiscord#205]
**Describe the bug**

Lack of ability to mass delete a Deleted User's messages

**To Reproduce**

1) Ensure you are either an Administrator or have the Manage Messages permission.

2) Copy an ID of a Deleted User and put it into the Author ID field. Then copy the Guild ID and paste it in the Guild ID field and press start. 

3) This will result in the script asking to delete all of the messages in the server.

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.

```
N/A
```

**Affects** (Add an X to items that apply)
- [X] DMs
- [X] DM Groups
- [X] Channel
- [x] Channel (NSFW)
- [X] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Linux Mint 19.3 Tricia
 - Browser: Chromium | 90.0.4430.93 (Official Build) Built on Ubuntu

**Why this is important:**
If you deleted your account, and you realize you didn't delete all of your messages in a server, you can no longer mass delete them. This is bad because people who are good at doxing know that you can figure out who the Deleted User is just by copying the ID of the Deleted User, correlating that message to the deleted account. 

The victim is in a very bad spot, and (assuming he/she has the Manage Messages permission) has to manually delete each message one by one.

**Comment by iamlongpant** [comment]
This is an issue with Discord, there is something you could do to work around this but it would end up deleting all messages sent by all deleted users, require coding knowledge, and some time.

**Explanation**
All deleted users have the same ID (456226577798135808). This script uses the search API to obtain messages but trying to search for messages authored by this ID will return every message sent in the guild by anyone, making it impossible for this script to delete messages sent by deleted users. You can see this for yourself by searching for `from:456226577798135808` and then `from:<your id>`.

**Less than Ideal Workaround**
To work around this, you could download every message in the server (perhaps with a tool like [Discord History Tracker](https://dht.chylex.com/) aka DHT), extract all message IDs created by deleted users from the archive ([DHT archive documentation](https://github.com/chylex/Discord-History-Tracker/blob/master/src/tracker/savefile.js)), and then modify deleteDiscordMessages to take in an array of message IDs. This is obviously a less than ideal solution, it would delete all messages sent by all deleted users, it would take a while to get all the message IDs for a large server, you would need permissions to delete the messages, and you would need some coding knowledge, but it would work and it wouldn't be too difficult, provided you have the skills.

If you do decide to go down this route, I am able to help you if needed.

**Comment by Dreamurrrr** [comment]
Sorry for the late response, @iamlongpant.

I will let you know if I start working on some code to commit to this repo.
