### ISSUE TITLE
[Question] choosing range as dates instead of message IDs

### ISSUE THREAD

**Issue by CapoFantasma97** [victornpb/undiscord#210]
Is it possible to choose a range through dates instead of message IDs? If not, might it be added?

Also, what are these empty slots above the message ID slots? The documentation doesn't mention them.

![Immagine](https://user-images.githubusercontent.com/9368910/119963488-b0ac9780-bf97-11eb-9b35-ad7ba26b6904.png)

**Comment by abbydiode** [comment]
You're on a very outdated version of Undiscord. However the empty text fields in this screenshot are the fields for filling in a date range.

**Comment by CapoFantasma97** [comment]
> You're on a very outdated version of Undiscord. However the empty text fields in this screenshot are the fields for filling in a date range.

This issue is almost 2 years old and I closed it because it's stale and I never received any response...

**Comment by abbydiode** [comment]
> > You're on a very outdated version of Undiscord. However the empty text fields in this screenshot are the fields for filling in a date range.
> 
> This issue is almost 2 years old and I closed it because it's stale and I never received any response...

You're right, I didn't notice it was old. I got an email for it so I assumed it was just opened and immediately closed again. My bad.
