### ISSUE TITLE
[BUG] Ended because API returned an empty page

### ISSUE THREAD

**Issue by aaa234243** [victornpb/undiscord#213]
I've been deleting messages and it has worked perfectly all day until now where i've been faced with this issue on both firefox & chrome. 

I attempt to delete the messages and it works as usual and the start message is blue text stating:
**"Total messages found: amountOfMessages   (Messages in current page 25, To be deleted: 25, System 0)  Offset: 0 "**
And it deletes all messages up until 25 messages where the same blue text appears followed by a yellow message.
**"Total messages found: amountOfMessages   (Messages in current page 0, To be deleted: 0, System 0)  Offset: 0 "**
**"Ended because API Returned an empty page"** ( In yellow text )

Then stops & ends with the usual green text message displaying how long taken. No red text signifying crashes.

Used the search delay: 100 & Import delay: 1000 (default settings) and have also experimented with higher ones but doesn't make any change. My ping is normal between 100-300 or so and has been at that all day when i was deleting so that hasn't changed. 

EDIT after larryqiann's update: 
It didn't fix it entirely. It fixed it/worked temporarily for most of the day but suddenly idk why NOW after every 25 msgs **("Total messages found: amountOfMessages (Messages in current page 0, To be deleted: 0, System 0) Offset: 0 ")** is spammed fast asf many times until it gets to a moment where,  Yellow text describing the API is Going too fast with an unordinarily high MS around 29k+ and needs to cooldown?

EDIT:

PinkyLaRue's code had fixed this issue to an extent as the bug would appear from every 100-5000 or somewhere inbetween for me that is. 
By combining pinky's + larryqiann's code it's been working smoothly all day deleting without the bug appearing

**Comment by ali-o54** [comment]
I am also having the same issue, totally new to code and I have googled it and it looks like there are some fixes out there but I can't make any of them work.

**Comment by cpm9** [comment]
I've been having this issue constantly today. The program no longer works for me I just get this error everytime. I use the program pretty often and this is the first time I have got this error.

**Comment by larryqiann** [comment]
<img width="1010" alt="Screen Shot 2021-06-09 at 7 56 32 PM" src="https://user-images.githubusercontent.com/25872705/121457620-cf7a3900-c95c-11eb-9b34-4294c7ce219b.png">
I made some edits to the code that cause the program to continue to increment the offset until it finds something to delete.

the problem is, there are a LOT of empty pages, so you need to make sure to set the search delay to like 1-5 seconds otherwise you will get rate limited for a while. Make sure to watch the script and reload the page when its done to stop it, since my hack disables the ending logic.

**Comment by ali-o54** [comment]
I tried what you suggested, but unfortunately it doesn't seem to be working for me (I'm getting a parsing error, the code is not working). I'm super new to coding so if you have any tips or even if I could copy/paste your version into my script I would really appreciate it!

**Comment by ali-o54** [comment]
Ah, spoke too soon I had a typo and now it's working for me, thank you!

**Comment by aaa234243** [comment]
It worked! Thanks for the fix

**Comment by Zyxty9** [comment]
> <img alt="Screen Shot 2021-06-09 at 7 56 32 PM" width="1010" src="https://user-images.githubusercontent.com/25872705/121457620-cf7a3900-c95c-11eb-9b34-4294c7ce219b.png">
> 
> I made some edits to the code that cause the program to continue to increment the offset until it finds something to delete.
> the problem is, there are a LOT of empty pages, so you need to make sure to set the search delay to like 1-5 seconds otherwise you will get rate limited for a while. Make sure to watch the script and reload the page when its done to stop it, since my hack disables the ending logic.

Could you maybe post the code changes you made in a reply for example so i know for sure i did it right and i'm not just messing stuff up? I'm very new to coding but i keep getting this error message as well when trying to delete discord messages so I wanted to try your fix

**Comment by PinkyLaRue** [comment]
@victornpb 

Hi,

I have an easy fix for this issue:

Starting at line 216:
else {
            if (total - offset > 0) {
              //Increment offset by 25
              offset += 25;
              log.warn(`Offset  incremented. Current offset: ${offset}`);
              await wait(searchDelay);
              if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
              return await recurse();
            }
             log.warn('Ended because API returned an empty page.');
            return end();

Summary - Since everything is done in chunks of 25, if the system finds 1-25 messages it will delete them. If it finds 0 messages (but total-offset>0) it will increment the offset by 25 to skip the 25 non-deletable messages and recurse. If (total-offset <= 0) then it will still end.

Incrementing the offset by 1 each time is not ideal because you'll still be traversing huge chunks of dead messages.

I had the original problem described above earlier - I've been running this for several hours now and have deleted thousands of messages with no errors and no API-induced slowdowns.

**Comment by plcny** [comment]
> @victornpb
> 
> Hi,
> 
> I have an easy fix for this issue:
> 
> Starting at line 216:
> else {
> if (total - offset > 0) {
> //Increment offset by 25
> offset += 25;
> log.warn(`Offset incremented. Current offset: ${offset}`);
> await wait(searchDelay);
> if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> return await recurse();
> }
> log.warn('Ended because API returned an empty page.');
> return end();
> 
> Summary - Since everything is done in chunks of 25, if the system finds 1-25 messages it will delete them. If it finds 0 messages (but total-offset>0) it will increment the offset by 25 to skip the 25 non-deletable messages and recurse. If (total-offset <= 0) then it will still end.
> 
> Incrementing the offset by 1 each time is not ideal because you'll still be traversing huge chunks of dead messages.
> 
> I had the original problem described above earlier - I've been running this for several hours now and have deleted thousands of messages with no errors and no API-induced slowdowns.

how would we put this into say like tamper monkey

**Comment by PinkyLaRue** [comment]
> 
> 
> > @victornpb
> > Hi,
> > I have an easy fix for this issue:
> > Starting at line 216:
> > else {
> > if (total - offset > 0) {
> > //Increment offset by 25
> > offset += 25;
> > log.warn(`Offset incremented. Current offset: ${offset}`);
> > await wait(searchDelay);
> > if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> > return await recurse();
> > }
> > log.warn('Ended because API returned an empty page.');
> > return end();
> > Summary - Since everything is done in chunks of 25, if the system finds 1-25 messages it will delete them. If it finds 0 messages (but total-offset>0) it will increment the offset by 25 to skip the 25 non-deletable messages and recurse. If (total-offset <= 0) then it will still end.
> > Incrementing the offset by 1 each time is not ideal because you'll still be traversing huge chunks of dead messages.
> > I had the original problem described above earlier - I've been running this for several hours now and have deleted thousands of messages with no errors and no API-induced slowdowns.
> 
> how would we put this into say like tamper monkey

Hi,

If you go in Tamper Monkey and open up the script for UnDiscord -> edit (I'm using GreaseMonkey, not sure if TamperMoney is different)...

Look in lines 217-220 of the original code (deleteDiscordMessages.user.js) you should see this

} else {
if (total - offset &gt; 0) log.warn('Ended because API returned an empty page.');
return end();
}

Replace with this:

} else {
            if (total - offset > 0) {
              log.warn(`Offset  ${offset}`);
              offset += 25;
              //log.warn(`Offset  ${offset}`);
              await wait(searchDelay);
              if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
              return await recurse();
              log.warn('Ended because API returned an empty page.');
            }
            return end();
        }

**Comment by plcny** [comment]
> > > @victornpb
> > > Hi,
> > > I have an easy fix for this issue:
> > > Starting at line 216:
> > > else {
> > > if (total - offset > 0) {
> > > //Increment offset by 25
> > > offset += 25;
> > > log.warn(`Offset incremented. Current offset: ${offset}`);
> > > await wait(searchDelay);
> > > if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> > > return await recurse();
> > > }
> > > log.warn('Ended because API returned an empty page.');
> > > return end();
> > > Summary - Since everything is done in chunks of 25, if the system finds 1-25 messages it will delete them. If it finds 0 messages (but total-offset>0) it will increment the offset by 25 to skip the 25 non-deletable messages and recurse. If (total-offset <= 0) then it will still end.
> > > Incrementing the offset by 1 each time is not ideal because you'll still be traversing huge chunks of dead messages.
> > > I had the original problem described above earlier - I've been running this for several hours now and have deleted thousands of messages with no errors and no API-induced slowdowns.
> > 
> > 
> > how would we put this into say like tamper monkey
> 
> Hi,
> 
> If you go in Tamper Monkey and open up the script for UnDiscord -> edit (I'm using GreaseMonkey, not sure if TamperMoney is different)...
> 
> Look in lines 217-220 of the original code (deleteDiscordMessages.user.js) you should see this
> 
> } else {
> if (total - offset > 0) log.warn('Ended because API returned an empty page.');
> return end();
> }
> 
> Replace with this:
> 
> } else {
> if (total - offset > 0) {
> log.warn(`Offset ${offset}`);
> offset += 25;
> //log.warn(`Offset ${offset}`);
> await wait(searchDelay);
> if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> return await recurse();
> log.warn('Ended because API returned an empty page.');
> }
> return end();
> }

![image](https://user-images.githubusercontent.com/85709912/121618247-78e02e00-ca34-11eb-8c76-c315c9b53ecc.png)

**Comment by plcny** [comment]
> > > @victornpb
> > > Hi,
> > > I have an easy fix for this issue:
> > > Starting at line 216:
> > > else {
> > > if (total - offset > 0) {
> > > //Increment offset by 25
> > > offset += 25;
> > > log.warn(`Offset incremented. Current offset: ${offset}`);
> > > await wait(searchDelay);
> > > if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> > > return await recurse();
> > > }
> > > log.warn('Ended because API returned an empty page.');
> > > return end();
> > > Summary - Since everything is done in chunks of 25, if the system finds 1-25 messages it will delete them. If it finds 0 messages (but total-offset>0) it will increment the offset by 25 to skip the 25 non-deletable messages and recurse. If (total-offset <= 0) then it will still end.
> > > Incrementing the offset by 1 each time is not ideal because you'll still be traversing huge chunks of dead messages.
> > > I had the original problem described above earlier - I've been running this for several hours now and have deleted thousands of messages with no errors and no API-induced slowdowns.
> > 
> > 
> > how would we put this into say like tamper monkey
> 
> Hi,
> 
> If you go in Tamper Monkey and open up the script for UnDiscord -> edit (I'm using GreaseMonkey, not sure if TamperMoney is different)...
> 
> Look in lines 217-220 of the original code (deleteDiscordMessages.user.js) you should see this
> 
> } else {
> if (total - offset > 0) log.warn('Ended because API returned an empty page.');
> return end();
> }
> 
> Replace with this:
> 
> } else {
> if (total - offset > 0) {
> log.warn(`Offset ${offset}`);
> offset += 25;
> //log.warn(`Offset ${offset}`);
> await wait(searchDelay);
> if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> return await recurse();
> log.warn('Ended because API returned an empty page.');
> }
> return end();
> }

the error doesnt pop up anymore but the trash can thing doesnt pop up anymore and when i use the normal code it pop up so could you please double check

**Comment by aaa234243** [comment]
@PinkyLaRue 
Thanks for the help, but yea i'm having a similar issue of the trash can not being there with the new code, is there a way to fix this? Many thanks

**Comment by PinkyLaRue** [comment]
ok, I see what happened ...

When I pasted in the code, it removed the `. This in turn, is causing the JS to not compile correctly, which is why you don't see the trash can. 

Here is the code:
` } else {
            if (total - offset > 0) {
              log.warn(`Offset  ${offset}`);
              offset += 25;
              //log.warn(`Offset  ${offset}`);
              await wait(searchDelay);
              if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
              return await recurse();
              log.warn('Ended because API returned an empty page.');
            }
            return end();
        }`

**Comment by aaa234243** [comment]
@PinkyLaRue 
Thank you :), it's working now hopefully stays that way

**Comment by Snapyou2** [comment]
Dope thanks a lot ! That should be added to the code.

**Comment by gitgudgitgud** [comment]
> 
> 
> ok, I see what happened ...
> 
> When I pasted in the code, it removed the `. This in turn, is causing the JS to not compile correctly, which is why you don't see the trash can.
> 
> Here is the code:
> 
> ```
>  } else {
> 
>             if (total - offset > 0) {
> 
>               log.warn(`Offset  ${offset}`);
> 
>               offset += 25;
> 
>               //log.warn(`Offset  ${offset}`);
> 
>               await wait(searchDelay);
> 
>               if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> 
>               return await recurse();
> 
>               log.warn('Ended because API returned an empty page.');
> 
>             }
> 
>             return end();
> 
>         }
> ```

Hey, i suck at anything code related. I tried copy and pasting this new version you put but sadly my trash can icon still disappeared. sorry if this is annoying but any chance i could get some help? sorry and thanks

**Comment by aaa234243** [comment]
@PinkyLaRue Hey pinkey, thanks for before i used yours and larry qianns and also removed his to test just yours and for some reason it doesnt work. I mentioned whats happening under "LATEST EDIT".

**Comment by SudoSopa** [comment]
Some useful info I noticed, after getting the "API returned an empty page" bug, I search for my messages in the appropriate channel and simply get nothing on the first page, only on the second do messages show up.

![image](https://user-images.githubusercontent.com/32418998/122622570-be1ce500-d05e-11eb-8419-5206960f58ab.png)

![image](https://user-images.githubusercontent.com/32418998/122622690-2075e580-d05f-11eb-9ad8-5fb5bd243e0f.png)

**Comment by Nighterlev** [comment]
> 
> 
> ok, I see what happened ...
> 
> When I pasted in the code, it removed the `. This in turn, is causing the JS to not compile correctly, which is why you don't see the trash can.
> 
> Here is the code:
> 
> ```
>  } else {
> 
>             if (total - offset > 0) {
> 
>               log.warn(`Offset  ${offset}`);
> 
>               offset += 25;
> 
>               //log.warn(`Offset  ${offset}`);
> 
>               await wait(searchDelay);
> 
>               if (stopHndl && stopHndl() === false) return end(log.error('Stopped by you!'));
> 
>               return await recurse();
> 
>               log.warn('Ended because API returned an empty page.');
> 
>             }
> 
>             return end();
> 
>         }
> ```

So far this seems to be working perfectly.  I believe Discord possibly broke something on there side for this issue to happen at all.  I've been getting stuff like this pop up constantly now in random increments.  Looks like it's exactly what was going on to.  
![Screenshot_37](https://user-images.githubusercontent.com/44956068/122624425-c593bc80-d065-11eb-96df-b7cce68da921.png)
![Screenshot_38](https://user-images.githubusercontent.com/44956068/122624426-c6c4e980-d065-11eb-87bb-bda459329953.png)
![Screenshot_39](https://user-images.githubusercontent.com/44956068/122624427-c7f61680-d065-11eb-9137-d2fcae93e931.png)

**Comment by pSneakY** [comment]
i pasted the code and now i dont see the trash bin anymore

**Comment by pSneakY** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/86135778/122626621-96874600-d079-11eb-930c-106dd7ad4df8.png)

**Comment by pSneakY** [comment]
@Nighterlev i did the code you pasted it in but i dont see trash bin

**Comment by SudoSopa** [comment]
> i pasted the code and now i dont see the trash bin anymore

I pasted it as well and it worked fine. Most likely, you pasted it in wrong and now it doesn't compile. Your code should look exactly like how it does in the image below.

![image](https://user-images.githubusercontent.com/32418998/122626659-6f2c7b00-d071-11eb-8f47-742467d280c9.png)

**Comment by pSneakY** [comment]
oh wait it works now

**Comment by waltersoprano** [comment]
> > i pasted the code and now i dont see the trash bin anymore
> 
> I pasted it as well and it worked fine. Most likely, you pasted it in wrong and now it doesn't compile. Your code should look exactly like how it does in the image below.
> 
> ![image](https://user-images.githubusercontent.com/32418998/122626659-6f2c7b00-d071-11eb-8f47-742467d280c9.png)

Working smoothly after pasting this. Thank you so much.

**Comment by gqqjhffr** [comment]
I'm also having this exact issue, but this thread is difficult to parse for me because I'm unfamiliar with coding and have processing issues. Could someone compile the solution into a single, clearly labeled post?

**Comment by n3k2** [comment]
> I'm also having this exact issue, but this thread is difficult to parse for me because I'm unfamiliar with coding and have processing issues. Could someone compile the solution into a single, clearly labeled post?

https://pastebin.com/raw/PsnJhACM

have fun!
