### ISSUE TITLE
Deleting stops halfway, after i cannot continue

### ISSUE THREAD

**Issue by xItzGraciex** [victornpb/undiscord#217]
Hi there! I have been using this since yesterday and I really love it. Sadly after a while, the deleting stops halfway. When I press "start" again it says deleted 0 messages and 0 messages failed. Is there a way to fix it or do I have to wait for a while?

So example there are 500 messages , it stops at 250

**Comment by gqqjhffr** [comment]
I'm getting this too, except it maxes out at 25 messages per channel. I used to be able to just turn it on and let it delete all my messages in a whole server if allowed to continue long enough. Has something changed?

**Comment by xItzGraciex** [comment]
Ah yeah I tried again and it only deletes 25 messages

**Comment by vis2x** [comment]
same for me

**Comment by vis2x** [comment]
I found a solution to this bug [https://github.com/victornpb/deleteDiscordMessages/issues/213#issuecomment-859135729](here). Not sure if it's a permanent fix, but it fixes this current bug.
