### ISSUE TITLE
Empty Page

### ISSUE THREAD

**Issue by Seth1800** [victornpb/undiscord#220]
I was able to delete the messages just fine without specifically putting certain words for texts, but after i tried to start it again, it just said that it was an empty page when i had clearly said that it sees 6000 messages. It says that API returned an empty page

**Comment by Wexutar** [comment]
I have the same issue, since a half year..

**Comment by n3k2** [comment]
> I have the same issue, since a half year..

theres a fixed script for tampermonkey
https://pastebin.com/raw/PsnJhACM

**Comment by Wexutar** [comment]
> 
> 
> > I have the same issue, since a half year..
> 
> heres a fixed script for tampermonkey
> https://pastebin.com/raw/PsnJhACM

 Thank you for your answer.  Im not into coding or using Tampermonkey, but i installed it , paste the script, but i do not know how to run it, whenever i set it to enable, nothing happens.. Any help please?

**Comment by n3k2** [comment]
> Thank you for your answer. Im not into coding or using Tampermonkey, but i installed it , paste the script, but i do not know how to run it, whenever i set it to enable, nothing happens.. Any help please?

after you put the script into tampermonkey, go to a dm on discord and you should see a recycle bin top right corner
![image](https://user-images.githubusercontent.com/86260922/123522264-f78bcb00-d6c4-11eb-9e1c-21bda1ffedd9.png)
