### ISSUE TITLE
[Question] Can creators access the deleted messages?

### ISSUE THREAD

**Issue by Isaac4235** [victornpb/undiscord#222]
I think this is a wonderful project, but I have a quick question before I use it.

Once I delete the messages using "Undiscord", are the messages gone forever, meaning, even the creators of this project will not be able to access the deleted messages? or do they keep track of the deleted messages done by the Undiscord? (by having some sort of storage)

**Comment by Toby222** [comment]
Short of the logs you see while it's deleting, which are not stored anywhere, and whatever Discord tracks internally, there is no record kept anywhere.
