### ISSUE TITLE
Userscripts is a Safari extension that can run Undiscord.

### ISSUE THREAD

**Issue by Ziyph** [victornpb/undiscord#226]
**Is your feature request related to a problem? Please describe.**
This project's [readme.md](https://github.com/victornpb/deleteDiscordMessages/blob/master/readme.md) states that there is no extension that can run Undiscord in Safari, but, [Userscripts](https://github.com/quoid/userscripts) is an extension that can.

**Describe the solution you'd like**
[Userscripts](https://github.com/quoid/userscripts) should be listed as an extension that can be used to run Undiscord in Safari.

**Additional context**
![Userscripts](https://user-images.githubusercontent.com/57063197/126073696-ff934bbd-a598-4901-875c-a617e060110b.png)
![Discord](https://user-images.githubusercontent.com/57063197/126073814-fcdfc3b4-6d75-476c-ba49-9e107bdc54ee.png)

**Comment by victornpb** [comment]
Thank you, I was unaware of that extension. The setup is a bit cumbersome compared to Violent Monkey and TamperMonkey but I will update the Instructions
