### ISSUE TITLE
[BUG] Aborted by you

### ISSUE THREAD

**Issue by jetblock** [victornpb/undiscord#233]
Every time i run it, it immediately stops and says aborted by you. The confirmation window doesn't pop up.
![Screenshot_1](https://user-images.githubusercontent.com/87990505/127013933-87146bae-482f-4173-8a83-474d402ebf6c.png)

**Comment by Toby222** [comment]
Sounds like a duplicate of #230 ? Maybe try what they did.

**Comment by yada-yoda** [comment]
Just started to get this issue today, worked fine in the past for copy and paste version, now getting this error as well today.

**Comment by Heycate** [comment]
I got the same

**Comment by JoeMoura6** [comment]
last week worked fine, but yesterday and today i got this error
someone find the solution?

**Comment by taspeotis** [comment]
Could be [Feature: Remove alert(), confirm(), and prompt for cross origin iframes](https://www.chromestatus.com/feature/5148698084376576).

Solution would be to render an alert yourself.

**Comment by moritzuehling** [comment]
Workaround for people interested:

Press F12 / open the developer tools in the "delete messages" window.
In the developer console, paste the following:

```js
window.confirm = () => true;
```

Once you press start, it will work. Be careful, it will *not* ask for permission at all after this.
