### ISSUE TITLE
Not specifying anything

### ISSUE THREAD

**Issue by chnaski** [victornpb/undiscord#236]
Can't we just not specify anything such as dates and before/after ids and have it delete every message in the current channel youre in by default?

**Comment by grizzlybearclaws** [comment]
You don't have to specify dates and you don't have to specify before and after IDs either. You only need your authorization ID, your author ID, and your guild ID to start the Undiscord userscript. Channel IDs, dates and before and after IDs are only used for specifying.

![undiscord](https://user-images.githubusercontent.com/86576431/127957188-4dba823e-5b19-4cc1-8450-269538d9c7ce.png)
