### ISSUE TITLE
[Feature request] Archived threads need to be automatically skipped

### ISSUE THREAD

**Issue by ghost** [victornpb/undiscord#242]
When threads are archived by the owner or the moderator of the server, the thread cannot be archived. 

The Undiscord userscript needs to automatically detect when the user's messages in a thread is archived and automatically skip them, without having to make an attempt to delete and give the user an error message.

At the end of the deletion, users should see if there are still messages left, as they usually do. Obviously the remaining undeleted messages would be from the archived threads, and the user would have an estimate how many messages they left in the server from those archived threads. Alternatively, the script could also state that there were messages that can't be deleted. 

I've had many times the Undiscord userscript would try to delete a message, send me back an error message, move onto the next message, and repeat this pattern, making the deletion process a lot slower: 

![50083](https://user-images.githubusercontent.com/86576431/129431024-70c51234-f0e2-42fb-9ed7-708e79b1d6a0.png)

 I would like the Undiscord userscript to skip archived threads entirely because messages from archived threads cannot be deleted.

**Comment by grizzlybearclaws** [comment]
![50083(1)](https://user-images.githubusercontent.com/86576431/129431137-d6257f09-cd53-44b2-a9bc-75d689d257a8.png)

Another reason: the Undiscord will keep retrying attempts to delete user messages that are in archived threads, making the program run for an infinite amount of time.

**Comment by NoktyNx** [comment]
+1 this issue is a huge nuisance

**Comment by victorlee** [comment]
+1 this issue needs immediate attention

**Comment by sinnx3** [comment]
+1 on this. Clogs up the deletion queue especially when 15/25 of search results are from archived threads then on next search pull from the api it requeues those archived posts so it's in a constant loop. Severely impacts deletions.
