### ISSUE TITLE
[BUG] Unable to delete messages unless I include a new message

### ISSUE THREAD

**Issue by bad1080** [victornpb/undiscord#244]
first off: thank you very much for making this tool, it is very much appreciated!

**Describe the bug**
undiscord is unable to delete messages although it is finding them in the search

**To Reproduce**
1. it started with me unfriending someone that i still wanted to delete dm's from (and i deleted roughly 7k messages before this) 
2. now undiscord was unable to perform (understandably so)
3. added them back to friends (and they accepted the friends request)
4. undiscord can "see" the left over messages again (which went back to early 2020 at this point, not sure if that matters) but is unable to delete them unless:
5. i write a new message and include it in the deletion
6. this is repeatable 

**Screenshots / Logs**
with only old messages:
![Clipboard01](https://user-images.githubusercontent.com/77503004/129458882-b0c29c49-bd93-4112-8e79-2602f133e95e.jpg)
after including 4 new messages:
![image](https://user-images.githubusercontent.com/77503004/129459343-578e2477-ca05-432c-93b7-253edda69ae6.png)
another one:
![image](https://user-images.githubusercontent.com/77503004/129460254-d413060b-96b8-4130-a82f-06231cc821c6.png)

```
Paste logs here 
(not sure how tbh)
```

**Affects** 
- [x] DMs (haven't tested anything else)

**System:**
 - OS: Windows 10 64bit
 - Browser: Vivaldi 4.1.2369.16 (Stable channel) (64-bit)
 - Tampermonkey

**Comment by grizzlybearclaws** [comment]
The Undiscord userscript should work normally again when you refresh your tab. Either that or try to delete again. Sometimes the Undiscord userscript won't delete all messages the first try. I am not sure why.

**Comment by bad1080** [comment]
> The Undiscord userscript should work normally again when you refresh your tab. Either that or try to delete again. Sometimes the Undiscord userscript won't delete all messages the first try. I am not sure why.

i tried reloading and triggered the deletion multiple times and found this to be the only way to get the process going again
