### ISSUE TITLE
How to prevent being API rate limited?[Question] 

### ISSUE THREAD

**Issue by AnonymousMurid** [victornpb/undiscord#245]
I set my delay to be:
`const wait = async ms => new Promise(done => setTimeout(done, ms + Math.floor(Math.random() * 200) ));`
The search delay was 500 and the delete delay was 1500
I got rate-limited thrice because of this:

![discord API rate limit](https://user-images.githubusercontent.com/89221547/130150433-f9030267-023d-4fa2-829f-4ba84cbb2b82.PNG)

I later edited the numbers to be:
`const wait = async ms => new Promise(done => setTimeout(done, ms + Math.floor(Math.random() * 700) ));`
With 1000 search delay and 1500 delete delay.
However I got rate-limited within 4 minutes:

![api rate limited](https://user-images.githubusercontent.com/89221547/130150824-22b44062-8bcf-4d22-947e-62c686cf0046.PNG)

Could anyone advise me on how to prevent this from occuring?

**Comment by aaa234243** [comment]
Im also having a similar problem with the rate being limited after a certain while.

**Comment by Juan71287** [comment]
> I've found a workaround, i'm assuming it's an incremental delay where deleting in quick succession has you climb "levels" of rate limits, each level requiring more time without deletions in order to "come down", and past a certain point you end up getting stuck at the highest level with every next deletion keeping you stuck there
> 
> After `for (let i = 0; i < messagesToDelete.length; i++) {` add `if (i % 8 == 7) await wait(15000)`
> 
> It waits 15 sec every 8 messages. It's been running consistently for 40 min, deleted ~650 msg, and only hit one rate limit at around 15 min (because i was sending a lot of messages i believe)
> It's slower but at least it's usable, there are probably more efficient values but i won't waste more time on this "Disgrace"

How do you do this part? I am sorry, I am not good at this.

**Comment by Prismatique1337** [comment]
> I've found a workaround, i'm assuming it's an incremental delay where deleting in quick succession has you climb "levels" of rate limits, each level requiring more time without deletions in order to "come down", and past a certain point you end up getting stuck at the highest level with every next deletion keeping you stuck there
> 
> After `for (let i = 0; i < messagesToDelete.length; i++) {` add `if (i % 8 == 7) await wait(15000)`
> 
> It waits 15 sec every 8 messages. It's been running consistently for 40 min, deleted ~650 msg, and only hit one rate limit at around 15 min (because i was sending a lot of messages i believe) It's slower but at least it's usable, there are probably more efficient values but i won't waste more time on this "Disgrace"

where do u place `for (let i = 0; i < messagesToDelete.length; i++) {` add `if (i % 8 == 7) await wait(15000)`
