### ISSUE TITLE
Code-10008

### ISSUE THREAD

**Issue by nevedpaharia** [victornpb/undiscord#254]
> WARNING: Github Issues are publicly visible, do not post sensitive information here.
> You may want to use the "Screenshot mode" before taking screenshots or copying logs.

Describe what your question is, try to give as much detail as possible so I can help you.

Post screenshots if applicable.

**Comment by Toby222** [comment]
Describe what your question is, try to give as much detail as possible so I can help you.

Post screenshots if applicable.
