### ISSUE TITLE
[BUG] Not Deleting messages

### ISSUE THREAD

**Issue by grimze** [victornpb/undiscord#258]
*Ended because API returned an empty page.
![3MWcPdGv](https://user-images.githubusercontent.com/91127988/134161126-0660625c-0bc4-4ce5-b667-e806d6605428.png)

**Comment by crackychans** [comment]
Getting the same problem.  Worked fine last night.
It's able to delete the first batch (25 messages) on a previously untouched channel/conversation.  After the first round, unable to progress.  Receiving **"Ended because API returned an empty page."** when there are still entries to be deleted.

**Comment by Faeety** [comment]
seems like the problem comes from Discord's api when returning messages. (precisely the search param because when used like this `https://discord.com/api/v9/channels/id/messages` it works fine but when used with `search?author_id=id` it randomly doesn't work)

Example of a problematic returning body
```json
{
    "total_results": 206,
    "messages": [],
    "analytics_id": "REDACTED"
}
```

**Comment by DevWannabe-dot** [comment]
https://github.com/victornpb/deleteDiscordMessages/issues/257#issuecomment-924493753 seemed to solve my problem

**Comment by CodingButter** [comment]
I was able to continue to delete by entering the id of the last message into the "delete all message before id" field. I believe this happens when there are many calls since those do not get deleted. the that means there are no messages returned within the batch requested.

**Comment by IriaSomobu** [comment]
https://github.com/victornpb/undiscord/issues/257#issuecomment-924493753 has not solved my problem
