### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by ghost** [victornpb/undiscord#26]
I used your deleteDiscordMessages. It's extremely, EXTREMELY useful. I've managed to purge tens of thousands of messages. Do you have a donation anywhere? I'll glad donate you $5 USD.

**Comment by victornpb** [comment]
TYSM! I enabled the Sponsor button at the top of the page, it is a _buymeacoffee_ link, donations are processed through PayPal. Let me know if it works for you.

Thank you again for your support!

**Comment by victornpb** [comment]
@briansaturnino TYSM! I enabled the Sponsor button at the top of the page, it is a buymeacoffee link, donations are processed through PayPal. 

Thank you again for your support!
