### ISSUE TITLE
Preserve Pinned Messages doesn't work [BUG] 

### ISSUE THREAD

**Issue by Neocamelus** [victornpb/undiscord#260]
**Describe the bug**

"Include pinned" is unchecked. But the script erases all messages.

**Affects** (Add an X to items that apply)
- [X] DMs

**System:**
 - OS: Fedora 34
 - Browser: chrome 94

**Comment by gohamstergo** [comment]
still happening on 5.0.3

**Comment by DoggoSlayz** [comment]
still happening now
