### ISSUE TITLE
Deleting Chats I No Longer Can See[Question] 

### ISSUE THREAD

**Issue by SweatyMarty** [victornpb/undiscord#263]
I have my data package that was sent from discord, and I was wondering if there was a way to delete chats from past friends/servers that I can no longer see...?

All help is appreciated, thank you.

**Comment by i0Z3R0** [comment]
@SweatyMarty I don't think this is possible, since you don't have access to those chats. It's like trying to delete a message in a channel you don't have permission to send messages in.

**Comment by SweatyMarty** [comment]
Can confirm, when using the id's gathered from the data package I didn't have permission to delete said conversations. Thank you for the response!
