### ISSUE TITLE
[BUG] trys to delete 1 message 20 times but doesnt

### ISSUE THREAD

**Issue by fuklalo** [victornpb/undiscord#348]
<img width="773" alt="Screen Shot 2022-04-30 at 6 56 36 PM" src="https://user-images.githubusercontent.com/104703779/166129000-e4eba959-01c7-4eb3-b10d-d3b8cbdd3938.png">

worked yesterday and the day before but now its doing this

**Comment by buhanec** [comment]
Seems like the script is incorrectly treating `retry_after` on being rate limited as milliseconds rather than seconds, see [Discord docs](https://discord.com/developers/docs/topics/rate-limits).

An interim fix is to find all occurences of
```javascript
const w = (await resp.json()).retry_after;
```
and just mupltiply them by 1000:
```javascript
const w = (await resp.json()).retry_after * 1000;
```

**Comment by victornpb** [comment]
seems like a change on the API side, when I implemented this was api/v6, maybe it changed on api/v9.

I will push a fix
