### ISSUE TITLE
@match (Regex) suggestion

### ISSUE THREAD

**Issue by HideakiAtsuyo** [victornpb/undiscord#354]
Hello, I have a suggestion for regex even if I don't know how tamper monkey would use it exactly, just tried => https://regexr.com/6kp6m like this you would need only 1 `@match`, isn't it better ?

**Comment by victornpb** [comment]
I’m very fluent when it comes to regex but:

[`@match` only works on the protocol/scheme, host, and pathname of a URL.][1]  

To trigger off the query parameters, you can either use `@include` or use `@match` and also test the URL yourself.  
Note that the `@match` approach performs faster.
  
With `@include`, you can use a regex syntax. See, also [Include and exclude rules][2].

But the documentation seems to discourage of include.

I think match is more readable to end users, I would switch to include + regex is the match gets unsustainable 

  [1]: https://developer.chrome.com/docs/extensions/mv3/match_patterns/
  [2]: http://wiki.greasespot.net/Include_and_exclude_rules

**Comment by HideakiAtsuyo** [comment]
> 

Ah sad I didn't knew sorry :(
Is the verification performed only once or every time you load a new url ?
