### ISSUE TITLE
[BUG] Can not automatically fill Author ID on Firefox with Strict Mode enabled.

### ISSUE THREAD

**Issue by smatchcube** [victornpb/undiscord#356]
Hello,

**Description of the bug**
When I click on the "me" button to get the author ID in the undiscord panel, the author ID is not automatically filled.

**Details**
The `document.body.appendChild(document.createElement('iframe')).contentWindow.localStorage;` returns `Storage { length: 0 }` instead of the correct json with all the details (and the `user_id_cache` that we want to extract).
The bug only happens with [Strict Mode](https://support.mozilla.org/en-US/kb/enhanced-tracking-protection-firefox-desktop#w_adjust-your-global-enhanced-tracking-protection-settings) enabled in the Firefox settings.
Maybe this mode restrict access to the local storage and there is no way to fix this, I don't really know. :shrug:

**Steps to reproduce**
- Enable strict mode in Firefox.
- Click on the "me" button to extract the Author ID in the undiscord panel.
- Observe that the Author ID field is not filled.

**System:**
 - OS: Debian
 - Browser: Firefox 91.8.0esr (64-bit) (the version shipped by Debian).

Of course it's not an important bug and was already present in the previous versions (but not in the old version with the detached window). I'm mostly reporting the bug so other persons don't have to search the reason (strict mode).

Thanks.

**Comment by victornpb** [comment]
Discord tries to hide access to localStorage, I know at least a few ways of getting to it, I just went with the simplest way first. I don't use firefox so I'm not familiar with that mode, it has probably something to do with the fact im creating an iframe, and coincidentally this is how 99% of ads are embedded on pages. I have to install firefox and try to fix it later. Thanks for reporting this issue

**Comment by victornpb** [comment]
Thats weird, I installed Firefox 100 and tampermonkey, enabled strict mode, and it worked for me.
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/3372598/167228909-0eb52966-b235-4c40-8c7e-276673601b7e.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/3372598/167228960-1eabef13-f6ce-4a91-9008-eb3dee6297f4.png">

**Comment by smatchcube** [comment]
I tested on a fresh OS in a Fedora VM with both the normal Firefox version and the [Firefox ESR](https://www.mozilla.org/en-US/firefox/enterprise/) version. Indeed it works with the normal Firefox version and the bug only happens in the ESR version, which is the one installed by default on Debian. So the bug comes from the difference in the strict mode between both versions.
Firefox ESR is basically the normal Firefox version lagging behind in term of updates, so the bug should disappear in future updates.

**Comment by smatchcube** [comment]
It seems that one of the update of Firefox ESR resolved this issue.
