### ISSUE TITLE
[BUG] Can no longer delete all messages matching string

### ISSUE THREAD

**Issue by TyroneWatermelone** [victornpb/undiscord#361]
**Describe the bug**
Prior versions allowed bulk deletion, of all text containing a given string, in a server. The current version mandates that you go through each author. Total downgrade in functionality, killing the point for some server owners! Sad!

**To Reproduce**
1. Fill in your settings
2. Leave author ID blank
3. Author ID REQUIRED

**Affects** (Add an X to items that apply)
- [] DMs
- [] DM Groups
- [X] Channel
- [X] Channel (NSFW)
- [X] Server (All Channels)
- [] Other (explain)

**Comment by victornpb** [comment]
I’m sorry for the inconvenience I'll fix it shortly

**Comment by victornpb** [comment]
fixed in https://github.com/victornpb/undiscord/pull/371
should be available in greasyfork soon
