### ISSUE TITLE
[BUG] Broken Link -> Copy Paste Version

### ISSUE THREAD

**Issue by umuterozan** [victornpb/undiscord#362]
**Describe the bug**
https://github.com/victornpb/undiscord/blob/master/help/copyPaste.md  (readme sends to [deleteDiscordMessages.js](https://raw.githubusercontent.com/victornpb/deleteDiscordMessages/master/deleteDiscordMessages.js) but link is broken)

**To Reproduce**
1. Go to 'https://github.com/victornpb/undiscord/blob/master/help/copyPaste.md '
2. Click on 'Select and Copy this script: [deleteDiscordMessages.js](https://raw.githubusercontent.com/victornpb/deleteDiscordMessages/master/deleteDiscordMessages.js)'
4. See error : 404 Not Found

**Comment by victornpb** [comment]
Link fixed! now both methods are the same file, just different instructions.

**Comment by victornpb** [comment]
https://github.com/victornpb/undiscord/wiki/Copy-paste-method
