### ISSUE TITLE
Undiscord stops deleting after second try?

### ISSUE THREAD

**Issue by KitsuTheFloof** [victornpb/undiscord#365]
Not sure how to exactly  explain this but here's what happens.
**[Step 1]** 
![image](https://user-images.githubusercontent.com/90358192/167037045-93b1d010-8623-4653-991d-6aa33accbe3f.png)

**[Step 2]**
After it clears successfully the first time, go to another DM and fill out the 3 fields again

**What should happen?** 
After you try to purge a second time it won't work anymore which is annoying.

**Comment by andrewkm** [comment]
Can confirm this is happening ever since the latest version.
@victornpb

**Comment by victornpb** [comment]
can you check if was fixed in v5.0.2?

**Comment by andrewkm** [comment]
@victornpb this is now fixed. :)
