### ISSUE TITLE
[BUG] Trash bin icon doesn't show!

### ISSUE THREAD

**Issue by Scrut1ny** [victornpb/undiscord#367]
**Describe the bug**
The trash bin icon doesn't show. I correctly setup and installed everything, but the icon won't show up for some reason. );

**To Reproduce**
1. Install Firefox.
2. Install Tampermonkey extension.
3. Install Undiscord script.
4. go to discord and it wont be there.

**Screenshots / Logs**
![Capture](https://user-images.githubusercontent.com/53458032/167226469-385d2b59-1091-4641-bcd9-cd5f6f7127b3.PNG)

**Affects**
- [x] DMs
- [x] DM Groups
- [x] Channel
- [x] Channel (NSFW)
- [x] Server (All Channels)
- [x] Other (explain)

**System:**
 - OS: Windows 10 Pro 19044 (Latest)
 - Browser: Firefox v100

**Comment by victornpb** [comment]
I just installed Firefox 100 and Tampermonkey and it worked for me.
<img width="1286" alt="image" src="https://user-images.githubusercontent.com/3372598/167228567-e07a689f-c38f-4d18-9cb4-205624b16a38.png">

Could be an issue with another extension you might have, maybe?
Also make sure you install from GreasyFork, the OpenUserJS website is stuck in an oder version (some issue on their side).

**Comment by Scrut1ny** [comment]
Interesting, I installed the script straight from GreasyFork and always do. The other extensions I have are:
![Capture](https://user-images.githubusercontent.com/53458032/167229240-46fa0c08-dcb2-46c4-ad6d-ae7015fc7d0d.PNG)

**Comment by victornpb** [comment]
Thank you I will keep it in mind if someone has the same issue. Thank you for reporting back, I will add to the docs when I have time.

**Comment by CapoFantasma97** [comment]
I'm having this issue. I don't remember it happening months ago. Latest Firefox build.

I don't use HTTPS Everywhere, and I tried to disable a number of addons as well as Firefox's HTTPS only mode. The result is unchanged.

To double check, I tried on Edge and it works.
