### ISSUE TITLE
Revert to old browser bar.

### ISSUE THREAD

**Issue by andrewkm** [victornpb/undiscord#369]
Is there any way to revert to the old browser bar?
The new one with version 5 is very inconvenient.
It is far smaller, thus lacks viewing certain information at a glance without scrolling through to the side.
Requires accessing pointless grouped menus for basic stuff such as before/after ID deletion.
etc.

The old one was big, everything in one place, and much easier to navigate for daily operations.
@victornpb can you possibly allow us to select a default bar where the old one would be available?

**Comment by Sol-Mane** [comment]
Seconding this, the new UI is completely non-functional and makes you go through hoops to set things previously available at a glance.

**Comment by victornpb** [comment]
I'm sorry for the inconvenience, I increased the default size a bit. Also you can resize it to any size (from the bottom right, I'm working on adding resize from the left corner)
