### ISSUE TITLE
[BUG] nothing happens when i press start

### ISSUE THREAD

**Issue by quakeman00** [victornpb/undiscord#377]
When i press start with the version 5.0.2 and 5.03, nothing happens, is also tried reverting to old 4.0 and 3.0 version but these dont work anymore either (doesn't grab AUTH anymore) my browser is brave if it means anything. all other options seems to work (clear log, grab info / set date and message filters, but none of this means anything if nothing happens when pressing start.

**Comment by eth** [comment]
It works good mate, stop winge'n

**Comment by KitsuTheFloof** [comment]
> It works good mate, stop winge'n

Nobody asked you whether it worked SPECIFICALLY for you or not.

**Comment by KitsuTheFloof** [comment]
> When i press start with the version 5.0.2 and 5.03, nothing happens, is also tried reverting to old 4.0 and 3.0 version but these dont work anymore either (doesn't grab AUTH anymore) my browser is brave if it means anything. all other options seems to work (clear log, grab info / set date and message filters, but none of this means anything if nothing happens when pressing start.

Don't worry I had the same issue but it's working now.

**Comment by quakeman00** [comment]
> 

what was the fix?

**Comment by KitsuTheFloof** [comment]
> > 
> 
> what was the fix?

It's not working for me again I just went to try now :(

**Comment by User10987654321** [comment]
I'm getting the same error

**Comment by ofernandofilo** [comment]
[if the script doesn't run, try]
- disable EFF HTTPS Everywhere extension;
- open developer tools first [ctrl+shift+i or f12];
- change browser;

_o/
