### ISSUE TITLE
[BUG] Ended because API returned an empty page

### ISSUE THREAD

**Issue by CodeGirl120** [victornpb/undiscord#383]
**Describe the bug**

**To Reproduce**

**Screenshots / Logs**
If applicable, add screenshots and or copy log to help explain your problem.

```
Paste logs here
```

**Affects** (Add an X to items that apply)
- [ ] DMs
- [ ] DM Groups
- [ ] Channel
- [ ] Channel (NSFW)
- [ ] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: [e.g. Windows 10, macOS 10.15.0]
 - Browser [e.g. chrome 69, firefox 42.0]

**Comment by CodeGirl120** [comment]
<img width="533" alt="Screen Shot 2022-05-26 at 6 47 34 AM" src="https://user-images.githubusercontent.com/106312787/170473357-5ea00efc-9911-455e-bf1f-c70d64c8b7eb.png">

Script was running fine, then stopped and kicked back this error Ended because API returned an empty page.
It is now happening no matter what i do. Updated, reinstalled, refreshed, still happening. 

Any help would be appreciated!

**Comment by PineappleSnackz** [comment]
Try looking for the last message you sent, copy its ID, and then put it in the "Messages before:...".

**Comment by Liakh731** [comment]
> Try looking for the last message you sent, copy its ID, and then put it in the "Messages before:...".
I did this about 40 minutes ago, it's working perfectly now.
