### ISSUE TITLE
I used Undiscord way too fast and now my Discord crashes whenever I open that DM.

### ISSUE THREAD

**Issue by Auline** [victornpb/undiscord#388]
I wanted to delete my DMs with my ex for quite important and personal reasons, but seeing how long it would take to delete them at the standard speed, I got impatient and raised the speed way more than my Discord could handle. I can still start Discord without any problems, but as soon as I look at our DMs, it freezes and after a short while crashes and restarts, landing me back on the Friends Page. Is there any way I can fix this? I have tried uninstalling it and giving it full RAM priority but nothing seems to work. Is this a fairly common issue? If so, I'd be eternally grateful. Thank you in advance, even if you can't help, and thank you for reading this!

**Comment by Auline** [comment]
Oh, I remember another detail now; I can see my DMs with her perfectly fine on my mobile device (iOS). Discord only crashes on PC for me.

**Comment by kanetjuh** [comment]
Could you try to follow one of these many fixes from [this website?](https://appuals.com/fix-discord-keeps-crashing/) and tell me if it solved your problem?
