### ISSUE TITLE
[BUG] Won't delete anythin

### ISSUE THREAD

**Issue by Monodiac** [victornpb/undiscord#389]
Whenever i try and press start after doing all the right stuff it doesn't delete anything, please help

**Comment by wuodland** [comment]
Works fine, do elaborate the exact issue or close this issue.

**Comment by agamsol** [comment]
> Works fine, do elaborate the exact issue or close this issue.

For me it only deletes my messages and not all messages, I do have the MANAGE_MESSAGES permission

**Comment by wuodland** [comment]
> > Works fine, do elaborate the exact issue or close this issue.
> 
> For me it only deletes my messages and not all messages, I do have the MANAGE_MESSAGES permission
when you say "all messages" you mean other people's messages? You would need to update the author/user ID every time foe each user

**Comment by SethFalco** [comment]
You can target all authors, just omit the author field.
