### ISSUE TITLE
Nothing Happens When I Press Start

### ISSUE THREAD

**Issue by User10987654321** [victornpb/undiscord#394]
I saw this exact same issue posted less than a month ago, yet my usage of undiscord with violentmonkey on linux firefox recreates the bug perfectly.

**Comment by karjonas** [comment]
Same for me on Firefox. It works fine on chromium.

**Comment by ofernandofilo** [comment]
for me, the same behavior happened when using the EFF HTTPS Everywhere extension, which forces the use of HTTPS only. disabling the feature, the plugin works again, at least in Waterfox (fork of firefox).
