### ISSUE TITLE
Delete Delay no longer configurable

### ISSUE THREAD

**Issue by theprez98** [victornpb/undiscord#397]
I have a server where I delete all messages older than one week every Sunday. I typically use a delete delay of 4000ms which is slow but almost never hits the rate limit even for hundreds of messages. Today when I tried to configure undiscord, I could not edit the delete delay manually, and the up/down arrows were no longer present. Since undiscord has not been updated since May it is unclear to me why this is now an issue. Any suggestions?

**Comment by larryqiann** [comment]
There is a workaround to this. You can go to a server that has a channel that you cannot send messages to (e.g. the Rules channel) and then edit the delay there. The chat box focus problem will go away.

This is part of a set of changes to the way Discord in the browser steals focus to and from the chat box, which has caused no end of unhappiness to me.

**Comment by abbydiode** [comment]
Another workaround to this is to click the text fields for the delays and scroll while hovering over the field.

**Comment by PROGRESS478** [comment]
Yet another workaround is to copy paste the value into the text field instead of manually typing it.

**Comment by sbeeo** [comment]
or just use arrow keys up/down
