### ISSUE TITLE
[BUG] Indefinite loop when there are too many undeleteable messages in an archived thread in the target channel

### ISSUE THREAD

**Issue by aurorachan3570** [victornpb/undiscord#406]
**Describe the bug**
If there are too many errors threw out for "400 thread is archived" the script will be stuck in an indefinite loop

**To Reproduce**
Have a **large** amount of messages in a thread
Archive the thread
Select channel = the channel that contains the thread
Start 

**Screenshots / Logs**
![image](https://user-images.githubusercontent.com/67498765/185616674-a9d43cae-1d93-4d45-a1a8-f113f0ac44d9.png)

**Affects** (Add an X to items that apply)
- [ ] DMs
- [ ] DM Groups
- [X] Channel
- [X] Channel (NSFW)
- [X] Server (All Channels)
- [ ] Other (explain)

**System:**
 - OS: Debian 11
 - Browser: Chrome/104.0.0.0 Safari/537.36

**Temporary Solution**
Ignore **ALL** messages if the script detects it to be in an archived thread.

**Comment by akiyuee** [comment]
**Temporary Fix**:
--- WARN: This is my personal fix, I can't guarantee it will 100% work on prod.
Also, if a channel ID is selected it will ignore ALL threads, archived or not. 

Modify line 821 from:
```js
return (msg.type === 0 || (msg.type >= 6 && msg.type <= 21) || (msg.pinned && includePinned)) && (!regex || msg.content.match(regex));
```

to
```js
return (msg.type === 0 || (msg.type >= 6 && msg.type <= 21) || (msg.pinned && includePinned)) && (!regex || msg.content.match(regex) && (channelId ? msg.channel_id==channelId));
```

**Comment by abbydiode** [comment]
Unarchiving the thread in question makes the messages deletable again.

**Comment by akiyuee** [comment]
@abbydiode what if that thread is not owned by me, and it was archived by a moderator?

**Comment by abbydiode** [comment]
> @abbydiode what if that thread is not owned by me, and it was archived by a moderator?

If I'm not mistaken anyone can unarchive a thread, you do not need moderator permissions for this.

**Comment by akiyuee** [comment]
/shrug

Anyways the thread I was bumping into was archived over 1 year ago.
![image](https://user-images.githubusercontent.com/67498765/185680284-fd91b850-2e4c-473d-a9cd-cbc780dd13eb.png)

**Comment by abbydiode** [comment]
> /shrug
> 
> Anyways the thread I was bumping into was archived over 1 year ago. ![image](https://user-images.githubusercontent.com/67498765/185680284-fd91b850-2e4c-473d-a9cd-cbc780dd13eb.png)

https://support.discord.com/hc/en-us/articles/4403205878423-Threads-FAQ#h_01F9A1VV0J73QKZQXJ6YZ24YBD

**Comment by akiyuee** [comment]
@abbydiode nope, seems like the thread was locked by channel permission, not by a moderator.

**Comment by abbydiode** [comment]
Unarchiving the thread in question makes the messages deletable again.

**Comment by SmiVan** [comment]
This is by no means a resolved issue, it still persists.

Unarchiving is not always available to a user, and this infinite loop occurs once there are 25 messages in an archived thread (because of the way the search works).
