### ISSUE TITLE
[BUG] Nothing happens when I click start 

### ISSUE THREAD

**Issue by KitsuTheFloof** [victornpb/undiscord#433]
So when ever I try to initiate the delete process I see this in the Developer Console Logs

VM506:1 Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at getToken (userscript.html?name=Undiscord.user.js&id=3b5b3e8e-f673-42e5-8204-85850dd7e630:1206:17)
    at HTMLButtonElement.start (userscript.html?name=Undiscord.user.js&id=3b5b3e8e-f673-42e5-8204-85850dd7e630:1347:23)

**Comment by MoonpaiCreampai** [comment]
Are you using the old copy paste version or the browser extension stuff? The copy and paste version is extremely fickicky and even after an hour of moving things around and editing crap in the console it quit after 100 messages.

**Comment by KitsuTheFloof** [comment]
What do you mean?

**Comment by veryfluffybunny** [comment]
Same issue.

This happens with the browser extension version 5.0.3 installed through Greasy Fork. The issue is with `getToken()`, I think the localStorage keys have changed. `LS.token` is undefined.

**Comment by abbydiode** [comment]
Might be due to the update that lets you now switch between multiple accounts, I imagine some sort of collection of tokens is stored instead of a single one. I haven't had this happen on the 5.0.3 userscript version on Chrome myself however.

**Comment by veryfluffybunny** [comment]
Funnily enough I couldn't find anything in localStorage that looked like a token.

I pulled my token out of the authorization header and string searched all of localStorage and couldn't find it.

I think it's related to this: https://stackoverflow.com/a/71759611

When I entered Responsive Design Mode in web developer tools then both `token` and `tokens` fields on localStorage got populated.
