### ISSUE TITLE
Unable to use this script

### ISSUE THREAD

**Issue by JustPoppy** [victornpb/undiscord#473]
### Undiscord Version

v5.2.0

### Browser

111.0.5563.110 (Official Build) (arm64) 

### Extension

VioletMoney

### Reproduction steps

I just tried to use the app

### Actual results

This channel isn't indexed yet. Waiting 2000ms for discord to index it...
Error searching messages, API responded with status 500!
	{"message":"500: Internal Server Error","code":0}

### Expected results

/

### Bug affects

- [ ] DMs
- [ ] DMs (group)
- [ ] Channels
- [ ] Channel (NSFW)

### Additional information & file uploads

![Screenshot 2023-03-25 at 23 33 45](https://user-images.githubusercontent.com/32400296/227745491-ac7e5831-123a-4b79-bae2-ed0ef330d069.png)

**Comment by Dis04** [comment]
Having this same issue.

**Comment by victornpb** [comment]
#471

**Comment by 1pauliewalnuts1** [comment]
Any fix?
