### ISSUE TITLE
[BUG] Not Deleting All Messages

### ISSUE THREAD

**Issue by seniorm0ment** [victornpb/undiscord#55]
**Describe the bug**
When running deleter on a channel, it deletes most of the messages, I then ran through all messages on each channel of the group, but if I do a from:username, stuff that I pinned (the actual pin message, not the content I pinned) shows up, and also a few random messages still never got deleted (just messages, emotes, etc.) which should've. Not sure why. It seems to be detecting all my messages, I ran it in one chat, and ran through like 8k+ messages no errors. I ran it over again and it said nothing to delete, but it seems like there is.

**System:**
 - OS: Win10
 - Browser: Firefox ESR

**Comment by mhannigan** [comment]
I have run into a similar problem where not all messages are deleted.  In my case, it often does this with many messages.  For example, out of 9,000+ messages, it deletes 100.  I keep running it on the same DM and it says that a blank page was returned.

What makes it work somewhat:  If I put something in the search field like "a", it will now delete more of the messages.  Still not all, but in this particular case, another 2,000.

OS: Win10
Browser: Chrome

**Comment by victornpb** [comment]
The script relies into the discord search, and as fair as I can tell in some cases the search pagination gets out of sync. I couldn't figure out exactly when it happens as I don't have that much stuff to delete, unless I generate something in order to test.

A useful piece of information would be if you just use the app search for `from:me` and see if it really returns "no results" or if maybe I'm doing something wrong.

**Comment by devyboy** [comment]
Essentially what's causing this is discord doesn't have those messages cached on the browser and can't request them for some reason. What I did to solve this was go to the channel I wanted to delete messages from, press on the scroll wheel on my mouse, and move my cursor to the top of the browser. This causes the chat to scroll up indefinitely, fetches all the messages, and allows them to be deleted.

**Comment by kaelosthereckoning** [comment]
I was able to replicate this error with plenty of results still returned by Discord's search feature. Made sure one of my messages was in the active window in case it was an issue pulling chat which was not being directly shown at run time, but Undiscord still found no messages to delete. Circumvented it by repeating the process with the letter 'a' in Undiscord's search feature and it successfully found and deleted hundreds of messages. Working my way through the alphabet, which may be a temporary solution for others / help isolate the issue.

**Comment by TheDuchy** [comment]
Somewhat fixed by replacing the order in which messages are sorted in the search.

replace "desc" on https://github.com/victornpb/deleteDiscordMessages/blob/master/deleteDiscordMessages.js#L204 with "asc"

**Comment by lazzyn** [comment]
> Somewhat fixed by replacing the order in which messages are sorted in the search.
> 
> replace "desc" on https://github.com/victornpb/deleteDiscordMessages/blob/master/deleteDiscordMessages.js#L204 with "asc"

This worked for me.
