### ISSUE TITLE
Discord Script Manager Error: API Status 400 - Cannot Execute Action on This Channel Type (Code: 50024)

### ISSUE THREAD

**Issue by djoudx** [victornpb/undiscord#651]
### Undiscord Version

latest

### Browser

Thorium	124.0.6367.218 (Official Build) (64-bit) 

### Extension

violentmonkey

### Reproduction steps

1. well just got my data requested from discord added the index.json file in the archive so i can delete my whole messages in discord there's some servers i left and all but i think undiscord skip those

### Actual results

got the following error 
![thorium_LPE509NwQs](https://github.com/user-attachments/assets/77254db7-e377-4fce-ae7e-9e5e9397e1ce)

### Expected results

undiscord should start deleting messages but it didn't

### Bug affects

- [X] DMs
- [X] DMs (group)
- [X] Channels
- [X] Channel (NSFW)

### Additional information & file uploads

![thorium_LPE509NwQs](https://github.com/user-attachments/assets/f2dc1543-cc6d-42da-b30e-eeac4d56fec6)

**Comment by realBernieReid** [comment]
The developer of this extension has announced on his telegram that he's no longer interested in helping people with the error. Just uninstall and learn how to use python.

**Comment by djoudx** [comment]
> The developer of this extension has announced on his telegram that he's no longer interested in helping people with the error. Just uninstall and learn how to use python.

Thank you for letting me know. It's a bit disappointing to hear that the developer is no longer providing support.

**Comment by djoudx** [comment]
Never mind, I found another project that works great. For anyone interested, check out this link: https://github.com/prathercc/discrub-ext.
