### ISSUE TITLE
Undiscord With all PR's Merged

### ISSUE THREAD

**Issue by VendorAttestation** [victornpb/undiscord#655]
### Undiscord Version

v6.0.0

### Browser

127.0.0.0

### Extension

TamperMonkey

### Reproduction steps

https://github.com/VendorAttestation/undiscord-reborn

I have merged all notiable PR's

### Actual results

https://github.com/VendorAttestation/undiscord-reborn

I have merged all notiable PR's

### Expected results

https://github.com/VendorAttestation/undiscord-reborn

I have merged all notiable PR's

### Bug affects

- [ ] DMs
- [ ] DMs (group)
- [ ] Channels
- [ ] Channel (NSFW)

### Additional information & file uploads

https://github.com/VendorAttestation/undiscord-reborn

I have merged all notiable PR's

**Comment by Clyde6790pGIT** [comment]
Works insanely well

**Comment by ebergstedt** [comment]
Thank you, works well

**Comment by VendorAttestation** [comment]
> This errors out if the entire page is full of something that got skipped (like applications). `CoreException {"stack":"TypeError: Cannot create property 'asc' on number '0'\n at UndiscordCore.run (chrome-extension://mfdhdgbonjidekjkjmjaneanmdmpmidf/userscript.html?name=Undiscord.user.js&id=68d03934-e41d-4cd7-bec1-5981da4ff1e6:771:50)\n at async HTMLButtonElement.startAction (chrome-extension://mfdhdgbonjidekjkjmjaneanmdmpmidf/userscript.html?name=Undiscord.user.js&id=68d03934-e41d-4cd7-bec1-5981da4ff1e6:1862:8)","message":"Cannot create property 'asc' on number '0'"} Waiting 16.70s before next page...`
> 
> The hour of ETA is also vastly incorrect: `Estimated time remaining: 311831600h 9m 25s` The ping function also doesn't seem to function correctly: `Delete delay: 1700ms, Search delay: 16700ms Last Ping: 1724414409772ms, Average Ping: 2132490777ms`

Feel free to make PR i just merged them all so it works

**Comment by VendorAttestation** [comment]
I have moved to https://github.com/prathercc/discrub-ext its better iirc so closing this
