### ISSUE TITLE
Skip empty pages feature

### ISSUE THREAD

**Issue by Tom2232** [victornpb/undiscord#80]
Hi! I've run into some troubles while using this script (very useful btw!) 
Sometimes I get the error "Ended because API returned an empty page." and in fact,when i scrool through messages (using discord search option) pages are in fact totally blank.
full message i get is "Total messages found: 30700	(Messages in current page: 0, Author: 0, System: 0)	offset: 0
Delete delay: 100ms, Search delay: 100ms	Last Ping: 532ms, Average Ping: 532ms
Estimated time remaining: 5h 25m 25s
Ended because API returned an empty page."
and if possible,option to skip those empty pages would be great addition

**Comment by victornpb** [comment]
It could easily be changed to ignore empty pages, but then there's no finish condition.
Currently, this is the way the script knows when there's nothing more to be deleted. The "total" isn't always accurate.
